# Generated by Django 6.0 on 2026-01-08 02:05

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=100)),
                ('diretor', models.CharField(default='', max_length=100)),
                ('cnpj', models.CharField(default='', max_length=18)),
                ('razao_social', models.CharField(default='', max_length=250)),
                ('telefone', models.CharField(default='', max_length=11)),
                ('celular', models.CharField(default='', max_length=12)),
                ('cidade', models.CharField(default='', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Observador_tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=150, null=True)),
                ('cpf', models.CharField(blank=True, max_length=150, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('documento_identificacao', models.FileField(blank=True, null=True, upload_to='documentos_observador_tecnico/', verbose_name='Documento de Identificação')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='fotos_observador_tecnico/')),
                ('cargo', models.CharField(blank=True, max_length=150, null=True)),
                ('clube', models.CharField(blank=True, max_length=150, null=True)),
                ('telefone', models.CharField(default='', max_length=11)),
                ('estado', models.CharField(blank=True, max_length=150)),
                ('cidade', models.CharField(blank=True, max_length=150)),
                ('endereco', models.CharField(blank=True, max_length=150)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('certificacoes', models.TextField(blank=True, null=True, verbose_name='Certificações')),
                ('certificacoes_arquivo', models.FileField(blank=True, null=True, upload_to='certificacoes_observador_tecnico/', verbose_name='Comprovante de Certificações')),
                ('categorias_interesse', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SUB7', 'Sub-7'), ('SUB8', 'Sub-8'), ('SUB9', 'Sub-9'), ('SUB11', 'Sub-11'), ('SUB13', 'Sub-13'), ('SUB15', 'Sub-15'), ('SUB17', 'Sub-17'), ('SUB20', 'Sub-20')], max_length=100, null=True, verbose_name='Categorias de Interesse')),
                ('posicoes_preferenciais', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('GOL', 'Goleiro'), ('LD', 'Lateral Direito'), ('LE', 'Lateral Esquerdo'), ('ZAG', 'Zagueiro'), ('VOL', 'Volante'), ('AD', 'Ala Direito'), ('AE', 'Ala Esquerdo'), ('MC', 'Meia/Meia Central'), ('MLE', 'Meia Lateral Esquerdo'), ('MLD', 'Meia Lateral Direito'), ('MAD', 'Meia Atacante Direito'), ('MAE', 'Meia Atacante Esquerdo'), ('ATA', 'Atacante'), ('CA', 'Centroavante'), ('PON', 'Ponta')], max_length=50, null=True, verbose_name='Posições Preferenciais')),
                ('notificacoes', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='core.escola')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascimento', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('escola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.escola')),
                ('time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.time')),
            ],
        ),
    ]
