# Generated by Django 6.0 on 2025-12-23 15:02

from django.db import migrations

def criar_grupos(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')

    for nome in ['Escola', 'Aluno', 'observador_tecnico']:
        Group.objects.get_or_create(name=nome)

class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(criar_grupos),
    ]